### ISSUE TITLE
Error not work math: static 

### ISSUE THREAD

**Issue by semiromid** [oddbird/susy#566] opened 2016-01-25 06:43 UTC
```
$susy: (   container: auto,   columns: 12,  // The number of columns in your grid   gutters: 1/4, // The size of a gutter in relation to a single column   //output: isolate   math: static );
```
Error: Function valid-column-math finished without @return
        on line 154 of C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/susy-2.2.11/sass/susy/language/susy/_span.scss, in `span'
        from line 43 of E:/Developers/WebDeveloper/OpenServer-WebProg/domains/scss-test/sass/style.scss, in `@content'
        from line 62 of C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/breakpoint-2.5.0/stylesheets/_breakpoint.scss, in `breakpoint'
        from line 39 of E:/Developers/WebDeveloper/OpenServer-WebProg/domains/scss-test/sass/style.scss

**Comment by mirisuzanne** [comment] 2016-01-25 16:50
This is a duplicate of #562

**Closed by mirisuzanne** 2016-01-25 16:50 UTC
